### ISSUE TITLE
run txmlconnector server on arm64

### ISSUE THREAD

**Issue by kmlebedev** [kmlebedev/txmlconnector#9]
Install box64 and winehq-stable:amd64 https://forum.armbian.com/topic/19526-how-to-install-box86-box64-wine32-wine64-winetricks-on-arm64/ ver 6.0.2  because https://github.com/ptitSeb/box86/issues/516

```
root@orangepi-rk3399:/usr/local/bin# box64 /usr/local/wine/bin/wine64 /tmp/server.exe
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 95622ca built on Oct 23 2022 23:02:01
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 27 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="/tmp/server.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 95622ca built on Oct 23 2022 23:02:01
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 28 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="/tmp/server.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 95622ca built on Oct 23 2022 23:02:01
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 28 Env var
Looking for /usr/local/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/lib64/wine/../libwine.so.1
0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
Using emulated /usr/local/wine/lib64/wine/msvcrt.so
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 95622ca built on Oct 23 2022 23:02:01
BOX64: Wine64 detected, WINEPRELOADRESERVE="000400000-0004a1000"
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 30 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="C:\windows\system32\conhost.exe"
argv[2]="--unix"
argv[3]="--width"
argv[4]="185"
argv[5]="--height"
argv[6]="56"
argv[7]="--server"
argv[8]="0x10"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /usr/local/wine/lib64/wine/../libwine.so.1
Using emulated /usr/local/wine/lib64/wine/ucrtbase.so
Using emulated /usr/local/wine/lib64/wine/gdi32.so
Using emulated /usr/local/wine/lib64/wine/user32.so
Using emulated /usr/local/wine/lib64/wine/ucrtbase.so
Using emulated /usr/local/wine/lib64/wine/user32.so
Using emulated /usr/local/wine/lib64/wine/gdi32.so
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated /usr/local/wine/lib64/wine/ws2_32.dll.so
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
unexpected fault address 0x60140ccceb0
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x60140ccceb0 pc=0x14004bdc2]

goroutine 1 [running, locked to thread]:
runtime.throw({0x140535fbe?, 0x0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x65 fp=0xc000147240 sp=0xc000147210 pc=0x140039cc5
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:261 +0x125 fp=0xc000147288 sp=0xc000147240 pc=0x14004d165
runtime.semrelease1(0x104?, 0x4?, 0xc00010a6c0?)
        /usr/local/go/src/runtime/sema.go:172 +0x62 fp=0xc0001472d8 sp=0xc000147288 pc=0x14004bdc2
runtime.semrelease(...)
        /usr/local/go/src/runtime/sema.go:162
internal/poll.runtime_Semrelease(0x0?)
        /usr/local/go/src/runtime/sema.go:82 +0x1d fp=0xc000147300 sp=0xc0001472d8 pc=0x140062d3d
internal/poll.(*FD).destroy(0xc000088500)
        /usr/local/go/src/internal/poll/fd_windows.go:380 +0xc5 fp=0xc000147328 sp=0xc000147300 pc=0x1400d3505
internal/poll.(*FD).decref(0xc000088500?)
        /usr/local/go/src/internal/poll/fd_mutex.go:213 +0x53 fp=0xc000147348 sp=0xc000147328 pc=0x1400d1113
internal/poll.(*FD).Close(0xc000088500)
        /usr/local/go/src/internal/poll/fd_windows.go:395 +0x69 fp=0xc000147378 sp=0xc000147348 pc=0x1400d35c9
os.(*file).close(0xc000088500)
        /usr/local/go/src/os/file_windows.go:197 +0x56 fp=0xc0001473c8 sp=0xc000147378 pc=0x1400e03d6
os.(*File).Close(0x1?)
        /usr/local/go/src/os/file_posix.go:25 +0x25 fp=0xc0001473e0 sp=0xc0001473c8 pc=0x1400defa5
google.golang.org/protobuf/internal/detrand.binaryHash.func1()
        /Users/tochka/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:50 +0x26 fp=0xc0001473f8 sp=0xc0001473e0 pc=0x140117606
google.golang.org/protobuf/internal/detrand.binaryHash()
        /Users/tochka/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:68 +0x25c fp=0xc0001474c0 sp=0xc0001473f8 pc=0x14011759c
google.golang.org/protobuf/internal/detrand.init()
        /Users/tochka/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:38 +0x17 fp=0xc0001474d0 sp=0xc0001474c0 pc=0x140117657
runtime.doInit(0x14040bc80)
        /usr/local/go/src/runtime/proc.go:6321 +0x12d fp=0xc000147600 sp=0xc0001474d0 pc=0x140048f6d
runtime.doInit(0x14040bd00)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc000147730 sp=0xc000147600 pc=0x140048eb1
runtime.doInit(0x14040bc40)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc000147860 sp=0xc000147730 pc=0x140048eb1
runtime.doInit(0x14040bcc0)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc000147990 sp=0xc000147860 pc=0x140048eb1
runtime.doInit(0x14040ff80)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc000147ac0 sp=0xc000147990 pc=0x140048eb1
runtime.doInit(0x140411bc0)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc000147bf0 sp=0xc000147ac0 pc=0x140048eb1
runtime.doInit(0x14040f580)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc000147d20 sp=0xc000147bf0 pc=0x140048eb1
runtime.doInit(0x140410420)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc000147e50 sp=0xc000147d20 pc=0x140048eb1
runtime.doInit(0x140409b40)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc000147f80 sp=0xc000147e50 pc=0x140048eb1
runtime.main()
        /usr/local/go/src/runtime/proc.go:233 +0x1bf fp=0xc000147fe0 sp=0xc000147f80 pc=0x14003c3bf
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000147fe8 sp=0xc000147fe0 pc=0x140067501

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00003ffb0 sp=0xc00003ff90 pc=0x14003c796
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xb1 fp=0xc00003ffe0 sp=0xc00003ffb0 pc=0x14003c631
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00003ffe8 sp=0xc00003ffe0 pc=0x140067501
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1405757d8?, 0x140895640?, 0xc?, 0x14?, 0x1?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000041f90 sp=0xc000041f70 pc=0x14003c796
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc000041fc8 sp=0xc000041f90 pc=0x1400269ce
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc000041fe0 sp=0xc000041fc8 pc=0x14001b566
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x140067501
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000028070?, 0x1405f9e18?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000051f70 sp=0xc000051f50 pc=0x14003c796
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x140895bc0)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000051fa0 sp=0xc000051f70 pc=0x140024a53
runtime.bgscavenge(0xc000028070?)
        /usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000051fc8 sp=0xc000051fa0 pc=0x140025045
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000051fe0 sp=0xc000051fc8 pc=0x14001b506
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0x140067501
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1408962e0?, 0xc000106000?, 0x0?, 0x0?, 0xc000043f70?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000043e28 sp=0xc000043e08 pc=0x14003c796
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc000043fe0 sp=0xc000043e28 pc=0x14001a66f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x140067501
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:157 +0x45
```

**Comment by kmlebedev** [comment]
hello word works

```
box64 /usr/local/wine/bin/wine64 /tmp/main.exe
root@orangepi-rk3399:/tmp# box64 /usr/local/wine/bin/wine64 /tmp/main.exe
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 95622ca built on Oct 23 2022 23:02:01
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 29 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="/tmp/main.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 95622ca built on Oct 23 2022 23:02:01
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 30 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="/tmp/main.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 95622ca built on Oct 23 2022 23:02:01
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 30 Env var
Looking for /usr/local/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/lib64/wine/../libwine.so.1
0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 95622ca built on Oct 23 2022 23:02:01
BOX64: Wine64 detected, WINEPRELOADRESERVE="000400000-0004a1000"
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 32 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="C:\windows\system32\conhost.exe"
argv[2]="--unix"
argv[3]="--width"
argv[4]="185"
argv[5]="--height"
argv[6]="56"
argv[7]="--server"
argv[8]="0x10"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /usr/local/wine/lib64/wine/../libwine.so.1
Using emulated /usr/local/wine/lib64/wine/ucrtbase.so
Using emulated /usr/local/wine/lib64/wine/gdi32.so
Using emulated /usr/local/wine/lib64/wine/ucrtbase.so
Using emulated /usr/local/wine/lib64/wine/user32.so
Using emulated /usr/local/wine/lib64/wine/user32.so
Using emulated /usr/local/wine/lib64/wine/gdi32.so
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated /usr/local/wine/lib64/wine/ws2_32.dll.so
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
Hello, world
```

**Comment by yarigpopov** [comment]
А что вы здесь хотите достичь? 
Запуска на arm64 или компиляции?

**Comment by kmlebedev** [comment]
> А что вы здесь хотите достичь? Запуска на arm64 или компиляции?

Запускать, через эмулятор win64 внутри эмулятор x86

**Comment by yarigpopov** [comment]
У меня на M1 запускается. Даже получается дебажить клиент в VSCode. У меня изначально была такая ошибка `Failed to launch: could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture`, но мне удалось победить ее с помощью https://stackoverflow.com/a/71381866

Еще пришлось переставить xcode-select и перебилдить goшные extentions в vscode
